import { InvalidEventRecord, TrialRecord } from '../types/experiment'

export const TRIAL_RECORD_COLUMNS: readonly (keyof TrialRecord)[] = [
  'sessionId',
  'participantId',
  'conditionId',
  'touchLocation',
  'menuLayout',
  'trialNumber',
  'targetId',
  'selectedId',
  'valid',
  'correct',
  'errorType',
  'cueTime',
  'touchDownTime',
  'touchUpTime',
  'selectionTime',
  'touchDownX',
  'touchDownY',
  'touchUpX',
  'touchUpY',
  'pathLength',
  'stageWidth',
  'stageHeight',
  'activationCenterX',
  'activationCenterY',
  'nearestEdgeDistance',
  'viewportWidth',
  'viewportHeight',
  'devicePixelRatio',
  'userAgent',
]

export const INVALID_EVENT_COLUMNS: readonly (keyof InvalidEventRecord)[] = [
  'sessionId',
  'participantId',
  'conditionId',
  'trialNumber',
  'targetId',
  'eventType',
  'eventTime',
  'pointerX',
  'pointerY',
  'stageWidth',
  'stageHeight',
  'activationCenterX',
  'activationCenterY',
  'viewportWidth',
  'viewportHeight',
  'devicePixelRatio',
  'userAgent',
]
